# Generated by Django 5.0.7 on 2024-07-14 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Index', '0002_alter_like_post_comment_reply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('picture', models.ImageField(upload_to='profile/pictures/')),
                ('desc', models.TextField()),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'female')], max_length=5)),
                ('universe', models.CharField(max_length=80)),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Index.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
