# Generated by Django 5.0.7 on 2024-07-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_remove_profile_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=6),
        ),
    ]
