# Generated by Django 5.0.7 on 2024-07-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_userpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPost',
        ),
    ]
