# Generated by Django 5.0.7 on 2024-07-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0003_alter_comment_user_alter_like_user_alter_post_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
